version: '3.7'

services:
  web:
      build: .
      ports:
          - '8080:8080'
      user: "node"
      env_file: .env
      restart: always
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data
volumes:
    database: