import { Stocks } from "@prisma/client";

export type difyReturn = {
  answer: string;
};

export type difyJson = {
  status: boolean; // if true, the operation is successful, else, the operation is failed
  message_for_client?: string; // message generated by AI to send to user
  items?: string[]; // items requested by the user
  database?: Stocks[]; // array with updated stock
  dev?: string; // message for dev in case of error, usually returns the reason why the request failed, generated by AI
};

export interface DifyInterface {
  /**
   * Request service to chat bot
   * @param stock array with database stock
   * @param message message sent by user
   */
  requestServiceToChatBot(
    stock: Stocks[],
    message: string
  ): Promise<difyReturn>;
}
